### ISSUE TITLE
ads/models and ads/AxonDeepSeg/models: Remove one

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/axondeepseg#151]
there are two "models/" folders. We should figure out which one is currently used, and remove the other one

**Comment by mathieuboudreau** [comment]
`ads/models` currently doesn't contain any actual model files, just a config_to_csv.py file which has some tools that might be useful (e.g. to compare models), but I don't think it's been used in a long time (last edited by @maxwab over a year ago) and I'm unsure if it's compatible with our current config files.

`ads/AxonDeepSeg/models` contains the current most up-to-date SEM and TEM models, however I think these should be moved outside the `ads/AxonDeepSeg/` folder since they don't actually contain code. Same goes with `ads/AxonDeepSeg/data_test/`, which only contains a test image & mask, and no actual code. `ads/AxonDeepSeg/` should only contain the ADS python package code, and all other resources should be moved outside of it.
