### ISSUE TITLE
Find a way to consistently find the ADS_logo via the FSLeyes plugin

### ISSUE THREAD

**Issue by Stoyan-I-A** [neuropoly/axondeepseg#201]
I managed to install FSLeyes and my AxonDeepSeg branch.
Here are the main steps I used  (on MacOSX) :
- I followed the ADS documentation to install ADS (Used miniconda, created a venv). The only difference is that I cloned my branch instead of the master, and my venv is called `integTest1`
- I used `conda install -c conda-forge fsleyes` to install fsleyes
- I launched FSLeyes with the command `fsleyes`
- Load plugin > ads_plugin.py > Yes

Then, when I tried to load the control panel, I got the following error :
![Screen Shot 2019-04-04 at 7 47 34 PM](https://user-images.githubusercontent.com/43790661/55596197-64e26880-5715-11e9-975a-67e67e45b171.png)

This is the code that is currently used to find the logo file : 
```
ads_path = Path(os.path.abspath(AxonDeepSeg.__file__)).parents[1]
logoFile = ads_path / 'docs' / 'source' / '_static' / 'logo_ads-alpha.png'
```
The 'docs' folder was simply not inside 'site-packages' 
Is there another/better way to find the logo file? 

That being said, as a temporary fix I just created the folders it was looking for and the plugin worked correctly. Therefore, the installation method I used should work correctly on MacOSX.

**Comment by mathieuboudreau** [comment]
I think the issue is the `parents[1]`. It should be `parents[0]` for you case, I'm guessing.

How did you install AxonDeepSeg? For me, it would only work for `parents[1]` if I recall. I would clone AxonDeepSeg, install it with `pip install -e .`, and so I think `AxonDeepSeg.__file__` wasn't in my venv folder, but the folder that I cloned it. But that may be because I would usually open FSL from that folder (or the cloned repo), and not another one (which would then "see" the ADS in the venv?). I can look into this more and see if I can reproduce your case; handling this correctly for all users cases is important, so thanks for letting us know.

**Comment by Stoyan-I-A** [comment]
I installed ADS using these commands :
```
conda create -n integTest1 python=3.6
git clone --single-branch --branch FSLeyes_integration https://github.com/neuropoly/axondeepseg.git
cd axondeepseg
pip install e .
```

**Comment by mathieuboudreau** [comment]
Hmm, interesting, that's how I do it too.

I think the main problem is that the image isn't within the module folder; it's outside of it. (i.e. `docs/`, which is where the image is, is outside the `AxonDeepSeg/` folder), so that because when you `import AxonDeepSeg` it's seeing the `AxonDeepSeg/` folder in your conda environment folder (which doesn't have the `docs/` one level above it) instead of the directory of your cloned repo (which does have that folder). We may want to include the image within the module folder, since it's now a necessary component of the software (and not just for documentation).

**Comment by Stoyan-I-A** [comment]
After changing to `parents[0]`, I get this error now :
![Screen Shot 2019-04-04 at 8 30 30 PM](https://user-images.githubusercontent.com/43790661/55596931-38305000-5719-11e9-9e80-1ad92c6025ef.png)

**Comment by jcohenadad** [comment]
> We may want to include the image within the module folder, since it's now a necessary component of the software (and not just for documentation).

Agreed

**Comment by mathieuboudreau** [comment]
That was just a guess. As I said, your module doesn't contain the image. A solution could be to move the image into the `AxonDeepSeg/` folder, then using `parents[0]` should work for both you and me.

**Comment by mathieuboudreau** [comment]
** and changing `logoFile = ads_path / 'docs' / 'source' / '_static' / 'logo_ads-alpha.png'` to `logoFile = ads_path / 'logo_ads-alpha.png'`

**Comment by mathieuboudreau** [comment]
@Stoyan-I-A I just pushed the changes I recommended to your branch/PR (commit caf663cbd0884d). Uninstall your AxonDeepSeg installation , re-install it, then reload your plugin, and see if it works. 

Check to be sure you didn't accidentally use `pip install axondeepseg`, because that's the only reason why I could see it in your `site-packages` of your env; for me, there is no AxonDeepSeg/ folder there when I install using `pip install -e .`, just an `AxonDeepSeg.egg-link` file containing this string "*/Users/mathieuboudreau/neuropoly/pr_review/axondeepseg/182*".

**Comment by Stoyan-I-A** [comment]
Thank you @mathieuboudreau 
I will try it either tomorrow or on Saturday.

**Comment by Stoyan-I-A** [comment]
It seems to work on Mac 👍 . I'll have to try it on Linux.

**Comment by Stoyan-I-A** [comment]
On Linux, there is a bug with wxPython where it can't properly resize images (instead of resizing the logo to 7% of its size, it will take the top-right corner of the logo that has the desired dimensions and display it). 
This makes the ADS logo invisible but the plugin still functions correctly.

A workaround is to resize the logo file manually and display the full-resolution-manually-resized logo.

**Comment by mathieuboudreau** [comment]
>A workaround is to resize the logo file manually and display the full-resolution-manually-resized logo.

Do you mean storing a copy of the logo with the correct size in the repository for the GUI, so you can avoid resizing it with wxPython? If so, then I agree, this seems like the best solution for cross-platform compatibility.
