### ISSUE TITLE
Implement AxonDeepSeg using Keras framework

### ISSUE THREAD

**Issue by mathieuboudreau** [neuropoly/axondeepseg#219]
Branch: [axondeepsegkeras](https://github.com/neuropoly/axondeepseg/tree/axondeepsegkeras)
Contributor: @vs74 

Other Issues: #217 
PRs: #216

**Comment by mathieuboudreau** [comment]
@vs74 could you add the new requirements & version to the [requirements.txt](https://github.com/neuropoly/axondeepseg/blob/axondeepsegkeras/requirements.txt) file in your branch, so that they are installed automatically? I think at least the cv2 and keras packages are missing

**Comment by vs74** [comment]
The codebase written in  TensorFlow  framework  is too complex to comprehend as it involves a lot of intricate details. Moreover it becomes difficult to exchange code of other architecture for experimentations, improvements or perform optimisations to existing model due to its verbosity. This issue aims at achieving the following things 
: - 
1. Replicate the ADS in TF framework to Keras framework.
2. Optimization and hypertuning of  ADS (SEM and TEM) model using Keras prebuilt libraries to achieve better performance.
3. Refactoring of ADS codebase (like train_network.py, apply_model.py, network_construction.py) alongside conversion to Keras framework.

**Comment by mathieuboudreau** [comment]
I thought the reason we were doing Keras over Pytorch was because we could reuse the framework code? If we need to rewrite the framework, shouldn't we go the PyTorch route instead?

**Comment by vs74** [comment]
Yes, the reason for the conversion to Keras over Pytorch  to TF is that is allows to use some TF code. Like for example ` apply_model.py ` needs less refactoring and it can be merged into Keras model by using Keras.backend as TF backend. On the contrary  some of the files needs to rewritten to Keras such as `network_construction.py`, `train_network.py` and `train_network_tools.py`. But I still thing moving to Keras is good decision as ADS is TF based.

**Comment by mathieuboudreau** [comment]
Thanks for clarifying!
