### ISSUE TITLE
Upload images and labels used to generate the models on public repository

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/axondeepseg#260]
The images and labels we used to generate ADS models should be made available on OSF, so that:
- it gives us an opportunity to version our models with a publicly-available dataset (excellent for comparison).
- it gives other groups an opportunity to test other approaches against ADS

**Comment by mathieuboudreau** [comment]
Should we upload this data to the AxonDeepSeg OSF, or your separate histology OSF project?

**Comment by jcohenadad** [comment]
I would suggest ADS OSF (for now)

**Comment by mathieuboudreau** [comment]
To do:

* [ ] Copy the folders */duke/projects/axondeepseg/raw_data/data_SEM* and */duke/projects/axondeepseg/raw_data/data_TEM*
* [ ] Delete all the other subfolders besides *3_done/*
  * @alzaia please confirm if that the training was done using any of the other subfolders (*0_to_segment/*, *1_to_correct/*, and *2_to_check/*), some of which have images in them.
* [ ] Cleanup *3_done/* so that it is in a format ready to be used by our data patching tool
  * should be *3_done/(folder)/(image.png + mask.png + pixel_size_in_micrometer.txt*)
  * SEM has the pixel sizes, but TEM doesn't. @jcohenadad or @alzaia, what was the pixel sizes of the raw TEM data acquired? And are they the same for all images (for SEM, they are not.)? The paper seems to suggest they are all 0.02, I just want to check.
* [ ] Copy *3_done/* for each SEM and TEM to more descriptive folder names for OSF
* [ ] Upload each to OSF
* [ ] Create patched data for training
* [ ] Upload patched data to OSF + training/validation/testing split details
  * I think this is important too, because differences in the final model could result in bad patching (from either us or other folks), e.g. interpolation method for masks.
* [ ] Train model
  * We need to do this again since I recently fixed our patching interpolation mode
  * Use @vs74 's data augmentation branch
* [ ] Upload model + training details
  * e.g. the commit # used for training & which OSF version of the patched data that was used.

One more thing to note is that the number of images in the folders don't agree exactly to how many were reported in the paper for SEM. I found 15 images, but only 12 are reported in the paper:

<img width="693" alt="Capture d’écran 2019-09-20 à 09 21 52" src="https://user-images.githubusercontent.com/1421029/65325102-8979b200-db88-11e9-8ca4-caa56fcc3286.png">

Also, I don't know which images exactly were used as test images (for both SEM and TEM, except for one SEM I believe since it's the same one as in our repository for testing). Can I arbitrarily choose the testing ones, or @jcohenadad do you want to try and match up the exact same training/validation/testing split as the paper ? (I don't know if this'll be possible, but I can try).

**Comment by mathieuboudreau** [comment]
Actually for TEM there is a guide in another folder for the splitting of the datasets. Not for SEM though.

TEM:

```
Training : 7 - 9 - 10 - 11 - 13 - 14 - 26 - 27 - 29 - 30 - 31 - 34 - 35 - 36
Validation : 15 - 25 - 28 Note : 25_0002 needed to be removed
Test : 12 - 32 - 33

Validation and tests id were drawn randomly.
then Creation of patches
```

I concur that 20160718_nyu_mouse_25_0002 does not contain a proper dataset (it only contains one file, image.png (missing the mask.png), and as shown below, is not actually a raw image file)

![image](https://user-images.githubusercontent.com/1421029/65326031-0dcd3480-db8b-11e9-8a6b-6899f1bdc894.png)

**Comment by jcohenadad** [comment]
>  @jcohenadad do you want to try and match up the exact same training/validation/testing split as the paper ? (I don't know if this'll be possible, but I can try).

no, let's be pragmatic and just upload a clean dataset, as heterogeneous as possible, and with ground truth as good as possible

**Comment by alzaia** [comment]
@mathieuboudreau You are right, only the samples under 3_done/ were used for the training.

**Comment by alzaia** [comment]
@mathieuboudreau and yes, all the TEM samples of the mouse splenium had the same pixel size.

**Comment by mathieuboudreau** [comment]
Done.

SEM: https://osf.io/vrdpe/
TEM: https://osf.io/uewd9/
