### ISSUE TITLE
Error after training finishes (Test image display issue?)

### ISSUE THREAD

**Issue by Paasu** [neuropoly/axondeepseg#289]
**Describe the bug**
After running the training file, the training runs fine but after it is done I get an error message which I am fully unsure what it is. The test image doesn't display either. I used a master version of branch from around early-mid February.
Console log: [error.txt](https://github.com/neuropoly/axondeepseg/files/4363126/error.txt)

**To Reproduce**
Run the training file.
Training file (Included both as notebook and python file): [training.zip](https://github.com/neuropoly/axondeepseg/files/4363143/training.zip)

**Desktop (please complete the following information):**
 - OS: [openSUSE]
 - Version [Leap 15.1]

**Comment by jcohenadad** [comment]
@Paasu it doesn't seem like you are using a venv as explained [here](https://axondeepseg.readthedocs.io/en/latest/documentation.html#virtual-environment)

**Comment by mathieuboudreau** [comment]
Actually, there also seems to be a missing import in a file.

[apply_modely.py](https://github.com/neuropoly/axondeepseg/blob/274ab3748e214f53c073f75cd6b98e1db84eab4f/AxonDeepSeg/apply_model.py) is calling numpy using `np`, so it should have an `import numpy as np` call at the top, and it doesn't. 

Tests didn't fail to flag us that, and they should have.

They didn't fail because apply_model is not tested in it's own test, but only through coverage of [integrity_test.py](https://github.com/neuropoly/axondeepseg/blob/8905c59f413283ea75e3314fe15720c034ef78f2/AxonDeepSeg/integrity_test.py) and/or other functions, which happens to import segmentation_scoring.py, which in turn imports numpy as np. 

Because @Paasu calls apply_model directly in his script, it's causing the error he's experiencing.

I'll do a quick fix and create a pull request; @Paasu you'll need to pull (redownload) the changes from master for it to be resolved for you.

**Comment by Paasu** [comment]
I downloaded the new version and ran the training.py in it but I get another error. 
[error2.txt](https://github.com/neuropoly/axondeepseg/files/4369462/error2.txt)

**Comment by vs74** [comment]
@Paasu, I tried to resolve the issue, could pull the recent changes mode in the #290 and see if it resolves your issue ?

**Comment by Paasu** [comment]
@vs74 Tried it on the changes you made and the new master branch I downloaded today, same error. For what it is worth, I have had to type import os in train_network.py everytime I have tried to train on a new AxonDeepSeg.

**Comment by mathieuboudreau** [comment]
@Paasu I think your config struct in the training.py file you shared is missing an option, which is what your error is indicating.

In the file you uploaded above, you would need to change

```

# Data augmentation parameters:
  "da-type": "all",  # Type of data augmentation procedure. Option "all" applies all selected data augmentation transformations sequentially, while option "random" only applies one of the selected transformations (randomly) to the sample(s). List of available data augmentation transformations: 'random_rotation', 'noise_addition', 'elastic', 'shifting', 'rescaling' and 'flipping'. 
  "da-0-shifting-activate": True, 
  "da-1-rescaling-activate": False,
  "da-2-random_rotation-activate": False,  
  "da-3-elastic-activate": True, 
  "da-4-flipping-activate": True, 
  "da-5-noise_addition-activate": False
```

to 

```

# Data augmentation parameters:
  "da-type": "all",  # Type of data augmentation procedure. Option "all" applies all selected data augmentation transformations sequentially, while option "random" only applies one of the selected transformations (randomly) to the sample(s). List of available data augmentation transformations: 'random_rotation', 'noise_addition', 'elastic', 'shifting', 'rescaling' and 'flipping'. 
  "da-0-shifting-activate": True, 
  "da-1-rescaling-activate": False,
  "da-2-random_rotation-activate": False,  
  "da-3-elastic-activate": True, 
  "da-4-flipping-activate": True, 
  "da-5-noise_addition-activate": False,
  "da-6-reflection_border-activate": False

```

**Comment by Paasu** [comment]
Thank you very much @mathieuboudreau everything seems to working fine. I did this on #290 and there is no current issues.
