### ISSUE TITLE
ADScontrol plug-in not loading in FSLeyes 0.33.1

### ISSUE THREAD

**Issue by amoebacodes** [neuropoly/axondeepseg#313]
**Describe the bug**
ADScontrol option not showing under Ortho View 1 dropdown list.

**To Reproduce**
*precondition: operated by someone with pretty much no coding experience who thinks that typing in Terminal is already a breakthrough in life
1. Update to latest Python (3.8)
2. Install updated version of AxonDeepSeg (with the following commands in virtual environment)

cd axondeepseg
git pull
pip install -e .

3. Passed quick test; had 6 warnings with comprehensive test. 
ERROR: Failed to generate report: No data to report.

4. Ignore previous message because quick test passed. 
5. Install 0.33.1 version of FSLeyes
6. open FSLeyes
7. file-->load plugin-->ads_plugin.py under folder name:/axondeepseg (file information: created today, so it must be the updated version, I assume?)
8. Look for ADScontrol tab, and it is not there :(

**Desktop (please complete the following information):**
 - OS: iOS
 - Version 10.15.4

This may just be that I messed up some lines of commands. Maybe I pasted them out of order? Because I am so new to all of this, any help is greatly appreciated. Thanks a lot!

**Comment by mathieuboudreau** [comment]
>*precondition: operated by someone with pretty much no coding experience who thinks that typing in Terminal is already a breakthrough in life

Congrats on getting this far already @amoebacodes! And thanks for opening your first issue! 🎉 Welcome to the GitHub community 😃.

So there's a few things that I think might be the issue. Since the comprehensive tests didn't pass, that means that one of the installation steps may not have been successful - no worries, we'll work it out!

First off, I'm assuming these (https://axondeepseg.readthedocs.io/en/latest/documentation.html#installation) are the steps you followed, however I just want to double check with you. 

If so, let's go through the checklist one by one, and maybe we'll be able to identify a step that resulted in the installation not being completely successful.

## Miniconda
* [ ] Do you have conda installed?
  * You can check this by typing this command in your terminal: `conda search python`. If it lists a lot of python versions, then you have it installed.
* [ ] If not, please install Miniconda in order to create a virtual environment later on in the installation using this service.
  * Since you're on a Mac, the instructions for installing Miniconda are the following: 
```bash
cd ~
curl https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -o ~/miniconda.sh
bash ~/miniconda.sh -b -p $HOME/miniconda
echo ". ~/miniconda/etc/profile.d/conda.sh" >> ~/.bash_profile
source ~/.bash_profile
```
* [ ] Test your installation by running the command `conda search python`. If it lists a lot of python versions, then you have it installed.

## Git

Great, now that that's done, we need to check to see if you have git installed. By reading your steps, it appears so, but I'll just add this in the checklist in case someone else online falls on this issue and are trying to resolve it as well.

* [ ] Check if you have git installed by typing the following command in the terminal: `git --help`. It should list all the options for git.
* [ ] If you don't already have it installed, please follow the installation instructions on the git downloads page: https://git-scm.com/downloads.

## Conda Virtual Environment

Now with that done, we need to create a virtual environment using conda, so that we don't mix some of the Python tools and packages already installed on your computer with the ones that we need for AxonDeepSeg. Skipping this step might result in conflicts between packages, and failing tests. We also use the conda environment to choose the exact version of Python we need to use AxonDeepSeg, which is currently version 3.7 (you mentioned that you installed version 3.8, so that might be one of the sources of your problems).

* [ ] Create a virtual environment by running the following command in your terminal: `conda create -n ads_venv python=3.7`
  * `ads_venv` is just the name that we chose for our example virtual environment. You can chose another name if you'd like (no spaces).
  * You'll likely be prompted with a question during the setup, please select [y]es.
* [ ] After that's done, activate the virtual environment with the command `conda activate ads_venv`
  * Let us know if you get a warning at this step. Sometimes `source activate ads_venv` is needed instead, but rarely.
  * Note that the virtual environment will need to be reactivated if you close your terminal and reopen it, or if you open a new tab.

## AxonDeepSeg installation

With that step done (and the virtual environment activated), now let's tackle installing AxonDeepSeg.

* [ ] Clone our GitHub repository with the command `git clone https://github.com/neuropoly/axondeepseg.git`
* [ ] Open that downloaded directory using `cd axondeepseg`
* [ ] Install AxonDeepSeg and the additional tools needed to run the software with the command `pip install -e .`
  * If you see any warnings, or red text, at this step please let us know. This might mean that there was a problem in creating or activating the virtual environment.
* [ ] Once that's done, let's skip the quick test command and go straight through to the comprehensive test (which runs the quick test and many more tests). You do so with the following command: `py.test --cov AxonDeepSeg/ --cov-report term-missing`
  * If some tests fail here, please provide a screenshot or copy-paste them. That might help us debug. However, if you followed all the instructions above and this step doesn't work, it might be best for us to schedule a video call with you so that we can see your steps (i.e. while screen sharing or something).

## FSLeyes plugin

If you've reached here and your tests are passing now, that'll be really encouraging! You're almost there!

* [ ] Still with the conda environment activated, install FSLeyes within it using the following command: `yes | conda install -c conda-forge fsleyes=0.33.1`
  * [ ] If you get an error relating to `yes`, it means that it's not installed on your computer. You can skip that command and simply run `conda install -c conda-forge fsleyes=0.33.1` and answer [y]es when prompted.
* [ ] After that's done, you could optionally run the comprehensive tests again just to check that installing FSLeyes didn't create any incompatibilities between software packages that are installed: `py.test --cov AxonDeepSeg/ --cov-report term-missing`
* [ ] Now, with the conda environment still activated, open FSLeyes with `fsleyes`
* [ ] On the FSLeyes interface, select `file -> load plugin -> select ads_plugin.py` (found in the cloned repository) 
  * [ ] When prompted with "Install permanently" , select "yes".
* [ ] Now, to see the AxonDeepSeg plugin, go to the top control bar and choose `Settings`, then `Ortho View`, and in the bottom you should see `ADScontrol` near the bottom of the list.
  * [ ] If all the steps above worked but you don't see `ADScontrol` at this step, this has happened to me once and I'm not sure why. I resolved it by closing FSLeyes, and reopening it with the command line command `fsleyes` (with the virtual environment activated).

## If that didn't work...

If you went through this entire checklist and are still having issues - let's schedule a videocall! Or if you're currently attending OHBM, come to one of our software demos (we have one today) =)

Hope some of this info helped!

**Comment by amoebacodes** [comment]
I cannot be grateful enough for your detailed, prompt instructions!! I appreciate that you explained the steps instead of simply pointing me to the documentation, which I thought I was already following. I am still having the same problem, and I am not sure why.

I do have Conda, Git, and have activated the virtual environment. These are the results from the first comprehensive test done right after installing ADS.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67404973/85745662-dff5bd00-b6d3-11ea-8257-c85b7dfff9f3.png">
<img width="192" alt="image" src="https://user-images.githubusercontent.com/67404973/85745845-03206c80-b6d4-11ea-8255-dadf33ab0555.png">
<img width="192" alt="image" src="https://user-images.githubusercontent.com/67404973/85745922-129fb580-b6d4-11ea-94d5-951296416f0a.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67404973/85745961-1a5f5a00-b6d4-11ea-9587-e49fb0922a8a.png">

This is what shows up after installing FSLeyes. Somehow there were more warnings?
<img width="601" alt="image" src="https://user-images.githubusercontent.com/67404973/85749327-c144f580-b6d6-11ea-9107-a7974f85b942.png">

I'm not sure if this is relevant, but this window pops up every time I open FSleyes. When I still could see ADScontrol before the update, it showed up too, and I just hit skip and ignored it.
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/67404973/85749534-ef2a3a00-b6d6-11ea-8acb-efd579ffd127.png">

My email is ywang381@jhu.edu, if you think that a video call is the best way to go from here. Or if you could kindly provide me a link to the software demo, it would be much appreciated too! Thank you so much, for real!!!

P.S. To any other coding beginners out there, I am sure you would be wiser and not make this stupid mistake, but here is what I did wrong. I operated everything following my messed up commands in the same Terminal window. I installed axondeepseg inside the file axondeepseg/ lol, so when I searched for it in my laptop, there were 6 different files with the same name. I deleted all of them, opened a new Terminal window, and did everything afresh.

**Comment by amoebacodes** [comment]
Not sure if this is relevant, but I just saw that you added one line to FSLeyes to downgrade indexed_gzip. I added it to my commands, but ADScontrol plugin still doesn't show up :(

**Comment by mathieuboudreau** [comment]
Want to come to our OHBM software demo? We're on there live talking about this  haha https://meet.jit.si/ohbm2020-1057. We'll be there for another hour or so

**Comment by mathieuboudreau** [comment]
Issue closed because issue was resolved by user. Better instructions in documentation were needed, and were added in #317
