### ISSUE TITLE
Error loading Image in FSLeyes

### ISSUE THREAD

**Issue by amoebacodes** [neuropoly/axondeepseg#319]
**Describe the bug**

Error loading overlay
Details: index must be completely built in order to seek from SEEK_END

**To Reproduce**
1. Comprehensive test passed
2. open fsleyes, load plug-in. ADScontrol is there after second try. Open ADScontrol.
3. Load png file.
4. Error message pops up
5. Load file from test image folder
6. See same error message

**Desktop (please complete the following information):**
 - OS: iOS
 - Version 10.15.4

Eh sorry for submitting an issue again. This time it is something different (awkward laugh). Thank you so much for your help earlier today, and thanks for bearing with me!!!

**Comment by mathieuboudreau** [comment]
Hi @amoebacodes !

We encountered that bug too today! It's because the most recent versions of one of our dependencies has a bug in it temporarily. You can resolved it by running this command after you've installed FSLeyes (while your virtual environment is activated):

`yes | conda install -c conda-forge indexed_gzip=1.2.0`

We added that instruction to the documentation this afternoon: https://axondeepseg.readthedocs.io/en/latest/documentation.html#graphical-user-interface-gui-optional

This should hopefully resolve your issue!

**Comment by amoebacodes** [comment]
Ohh right. I must not have refreshed the documentation page. Thank you for the reminder!!
