### ISSUE TITLE
Page build fails with symlink error

### ISSUE THREAD

**Issue by mariehbourget** [neuropoly/axondeepseg#420]
In PR #388, I added the symlink `docs/source/CHANGELOG.md` pointing to `../../CHANGELOG.md`.
This symlink was added in order to render the md file correctly in RTD. It was based on what was done in SCT [here](https://github.com/neuropoly/spinalcordtoolbox/blob/master/documentation/source/dev_section/CHANGES.md).

All tests passed and the doc is building properly.

However, since merging the PR, the github page build on master fails with an [error](https://github.com/neuropoly/axondeepseg/runs/1502787386) stating that the symlink target file does not exist. The path in the error is `/source/CHANGELOG.md`.

I'm not sure what I'm missing here, @kousu @joshuacwnewton, do you have an idea?

**Comment by joshuacwnewton** [comment]
Hmm. If I navigate to this page: https://axondeepseg.readthedocs.io/en/latest/CHANGELOG.html it shows the changelog.

Then if I click on "Edit in GitHub" it takes me to: https://github.com/neuropoly/axondeepseg/blob/master/docs/source/CHANGELOG.md which shows the symlink. So, it looks like on RTD everything is working OK.

>  the github page build on master fails with an [error](https://github.com/neuropoly/axondeepseg/runs/1502787386) stating that the symlink target file does not exist.

I'm a little confused about the build that is linked above. What is its purpose? If ReadTheDocs renders/hosts the documentation on its own, is this build action necessary?

**Comment by mathieuboudreau** [comment]
> I'm a little confused about the build that is linked above. What is its purpose? If ReadTheDocs renders/hosts the documentation on its own, is this build action necessary?

Yeah that's been bugging me too. Who set up this github action and why?

**Comment by joshuacwnewton** [comment]
I have a feeling it might be unnecessary. It references [GitHub Pages](https://pages.github.com/), which is a doc-hosting service that's entirely separate from RTD. (The GitHub Pages docs would show up here, I think: https://neuropoly.github.io/axondeepseg as opposed to https://axondeepseg.readthedocs.io)

I can't see ADS's settings because I don't have the necessary privileges, but if I had to guess, I'd say the setting below is enabled for the repo (from the main settings page). I think it's safe to turn this off.

![Screenshot from 2020-12-11 10-41-23](https://user-images.githubusercontent.com/16181459/101923553-89a30a80-3b9d-11eb-9cdc-678778c09a52.png)

**Comment by joshuacwnewton** [comment]
Ah, yes, here we are. GitHub Pages was indeed trying to build the site. 

![Screenshot from 2020-12-11 10-50-58](https://user-images.githubusercontent.com/16181459/101924544-d1766180-3b9e-11eb-8ccf-974e8c542743.png)

This is only useful if we wanted to use http://neuropoly.github.io/axondeepseg and ignore RTD entirely. But, since we use RTD instead, we can disable this and close the issue.

**Comment by joshuacwnewton** [comment]
All done. :slightly_smiling_face: 

And, for the future, for any docs-related builds or settings for ADS, this is where to go: https://readthedocs.org/projects/axondeepseg/

Everything looks A-OK: https://readthedocs.org/projects/axondeepseg/builds/

**Comment by jcohenadad** [comment]
thank you @joshuacwnewton !!
