### ISSUE TITLE
Documentation: Correction on GPU compatible installation of axondeepseg

### ISSUE THREAD

**Issue by dyt811** [neuropoly/axondeepseg#470]
**Describe the bug**

- Current documentation on how to install GPU compatible ADS cause ADS cli to crash
- For Full log and context: https://github.com/neuropoly/axondeepseg/discussions/469#discussioncomment-429709

**Steps To Reproduce**

1. Clone ADS Repo
2. Make the conda environment (no need to setup CUDA yet to reproduce this issue)
3. ```pip install -e .``` while in the conda env. 
4. ```pip uninstall tensorflow``` as per documentation here: https://axondeepseg.readthedocs.io/en/latest/documentation.html#gpu-compatible-installation
5. ```pip install tensorflow-gpu==1.13.1```
6. Reproduce the error reported in discussion

**Potential Fix**

1. replace ```tensorflow==1.13.1``` with ```tensorflow-gpu==1.13.1``` in the requirement.txt file.  Then run  ```pip install -e .```  while in the root directory of the repo. 
2. **ReadTheDoc/Sphinx documentation ultimately needs to update to reflect the above correct steps for that section.** 
3. Long discussion about the role of ```requirements.txt``` and potential better deployment strategy discussion as started in https://github.com/neuropoly/axondeepseg/issues/327 should continue. This may become a moot point or bigger issue when IvadoMed integration starts. 

**Platform (please complete the following information):**
 - OS: [Win 10.0.19042 Build 19042]
 - AxonDeepSeg version number: [git master]

**Comment by vs74** [comment]
So, I rechecked the instructions (https://axondeepseg.readthedocs.io/en/latest/documentation.html#gpu-compatible-installation) as mentioned on RTD for Bireli. 

Specs of Bireli
**CUDA:** 10.0
**CUDNN**: 7.4.2
**OS:** "Ubuntu"
**VERSION :** "16.04.6 LTS (Xenial Xerus)"

The instructions mentioned in the RTD work for Bireli and GPU is working perfectly fine. 

Then, I tried to install ADS on another Ubuntu machine with different CUDA and cuDNN version **CUDA: 11.0** and **no cuDNN** installed on this system. The specs are different from what is required by ADS (**CUDA: 10.0** and **CUDNN: 7.4.2**). Here, I got the same error as posted by the user. [#469 (reply in thread)](https://github.com/neuropoly/axondeepseg/discussions/469#discussioncomment-429709).

I believe the error is more from the incompatible **CUDA** and **CUDNN** version which is required by ADS than from the documentation instructions. In the discussion too, the user reported the *[*cuDNN** drivers missing](https://github.com/neuropoly/axondeepseg/discussions/469#discussioncomment-439048) which I think was the source of the error.

Conda lets a user download the correct CUDA and cuDNN versions in the virtual environment only. I found this way of working with GPU way more friendly because one doesn't need to spend a lot of time configuring, installing, updating, downgrading CUDA and cuDNN drivers.

All one needs is one line of code `conda install -c cudnn=7.3.1`.  This command downloads **CUDNN=7.3.1** and compatible **CUDA=10.0** on the machine in the virtual environment.


So, for second machine which was having `CUDA:11` and where I was having trouble working with TensorFlow gpu, I followed these instructions in a fresh virtual environment.

1. Install ADS ; `pip install -e .`
2. Install correct CUDA and cuDNN drivers ; `conda install -c anaconda cudnn=7.3.1`
3. Follow the GPU specific instructions as mentioned in RTD ; 
    3.1 `pip uninstall tensorflow`
    3.2 `pip install  tensorflow-gpu==1.13.1`
    
And these TensorFlow GPU works on this machine. 

I've tested these instructions on a Linux machine. @Stoyan-I-A / @dyt811, could you let me know if these instructions install tensorflow gpu correctly on a windows machine?

If this works, then perhaps we could instruct users to install CUDA and cuDNN drivers through `conda` in case they encounter such issues in the future.

**Comment by Stoyan-I-A** [comment]
> To test whether TensorFlow is using GPU, run this piece of code:
 ```
import tensorflow as tf
tf.test.is_gpu_available()      # If tf is using GPU, this will print `True`
```
This worked. It returned true.

However, once I try to run the command `axondeepseg_test`, I get the same error as in #469 , which is that axondeepseg requires tensorflow 1.13.1:
```
  File "C:\Users\Stoyan\Miniconda3\envs\ads_gpu_test_2\lib\site-packages\pkg_resources\__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'tensorflow==1.13.1' distribution was not found and is required by AxonDeepSeg
```
Now, I edited the `requirements.txt` file, I changed the line `tensorflow==1.13.1` to `tensorflow-gpu==1.13.1 `, reinstalled axondeepseg and ran `axondeepseg_test`. This time, it threw an error at the inference stage:
```
Beginning inference ...
processing patch 1 of 8
2021-03-13 20:31:14.745922: E tensorflow/stream_executor/cuda/cuda_dnn.cc:324] Loaded runtime CuDNN library: 7.3.1 but source was compiled with: 7.4.1.  CuDNN library major and minor version needs to match or have higher minor version in case of CuDNN 7.0 or later version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
```
Then at the end of the Traceback:
```
File "C:\Users\Stoyan\Miniconda3\envs\ads_gpu_test_2\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node cconv-d0-c0/convolution/conv2d_1/convolution}}]]
```

I guess that meant that I need to install CuDNN=7.4.1. However, when looking at the CuDNN downloads available with conda (https://anaconda.org/anaconda/cudnn/files), there isn't a 7.4.x version available.

I still tried with `conda install -c anaconda cudnn=7.6.4` and this time it worked.
I was able to run `axondeepseg_test` and it passed.
