### ISSUE TITLE
Implement more complete testing module

### ISSUE THREAD

**Issue by alzaia** [neuropoly/axondeepseg#76]
So far we only have a basic integrity test that installs the package and launches a segmentation on a test sample. We need to implement a complete testing module that will also test the other important functionalities (i.e. post-segmentation computations, metrics,...).

**Comment by mathieuboudreau** [comment]
Testing the input arguments of functions as well as their expected outputs would be great too. This would help tracking the stability of the API when developing.

For testing, have you considered using python's [unit testing framework](https://docs.python.org/2/library/unittest.html)?

**Comment by alzaia** [comment]
I was planning to use the [pytest](https://docs.pytest.org/en/latest/) framework. @mathieuboudreau any reason why you prefer the [unittest](https://docs.python.org/2/library/unittest.html) library instead?

**Comment by perone** [comment]
Just to complement, you can use unittest together with pytest without any problems. We integrated pytest+coverage in SCT also (https://github.com/neuropoly/spinalcordtoolbox/pull/1662) if you want to use it as a basis.

**Comment by mathieuboudreau** [comment]
@alzaia No strong preference on my side – I just thought of unittest since I've used it in the past, and I think it's already a default python package. I don't have experience with pytest, so I'm not sure of the additional benefits/features it provides over unittest.

**Comment by mathieuboudreau** [comment]
@alzaia I made some simple tests for get_pixeldata, along with some improved error handling, in branch [unit_tests](https://github.com/neuropoly/axondeepseg/tree/unit_tests) (commit [842643b](https://github.com/neuropoly/axondeepseg/commit/842643b64dadbac1b200be9f98fed695d03d30ae)). 

Please have a look to see if this is somewhat what you were aiming for, and if so I'll work on some more.

I think it would be good to have a consistent directory structure for the tests – I'm personally fond to having the test/ subfolders and files match the directory structure of AxonDeepSeg, with test files for each module (e.g test/morphometrics/test_compute_morphometrics.py for AxonDeepSeg/morphometrics/test_compute_morphometrics.py).

**Comment by alzaia** [comment]
Hi @mathieuboudreau, I do not have preferences, but this looks fine! Thanks a lot!

**Comment by mathieuboudreau** [comment]
@alzaia I fell on a small logical inconsistency while writing tests for `display_axon_diameter`.

https://github.com/neuropoly/axondeepseg/blob/5a0367c93f2e0972543c4d2eac745906ec57bc83/AxonDeepSeg/morphometrics/compute_morphometrics.py#L86-L96

The definition of the argument `path_prediction` isn't documented, but from lines 95-96 I'm assuming you meant it to be the '/path/to/file/AxonDeepSeg_seg-axonmyelin.png'.

As mentioned in the doc [here](https://neuropoly.github.io/axondeepseg/documentation.html#segment-a-single-image), "*The segmented acquisition will be saved in the same folder as the acquisition image, with the suffix ‘_seg-axonmyelin.png’*".

As a user, I'd expect that this is always the case, and from the code above (L95-96), so does that function [as well as other functions](https://github.com/neuropoly/axondeepseg/blob/5a0367c93f2e0972543c4d2eac745906ec57bc83/AxonDeepSeg/segment.py#L117-L118)

However, this file is not generated by `axondeepseg_test`, because `axon_segmentation()` has a default value for the segmentation filename to be `*AxonDeepSeg.png`:

https://github.com/neuropoly/axondeepseg/blob/5a0367c93f2e0972543c4d2eac745906ec57bc83/AxonDeepSeg/apply_model.py#L176-L180

instead of the call in `segment_image`, where it is forced to be *_seg-axonmyelin.png*:

https://github.com/neuropoly/axondeepseg/blob/5a0367c93f2e0972543c4d2eac745906ec57bc83/AxonDeepSeg/segment.py#L74-L84

As you can see from the `integrity_test()`, it's possible to call axon_segmentation without going through `segment_image`, which is was forcing the  *_seg-axonmyelin.png* suffix.

https://github.com/neuropoly/axondeepseg/blob/5a0367c93f2e0972543c4d2eac745906ec57bc83/AxonDeepSeg/integrity_test.py#L39

Should we remove the default argument value from the function, and force the suffix within axon_segmentation() instead of out of it?

**Comment by mathieuboudreau** [comment]
I added a test coverage badge (through coveralls.io) on the [unit test branch](https://github.com/neuropoly/axondeepseg/tree/unit_tests).

If you click on it, you can go see exactly which lines in each files are hit/missed by the unit tests.

**Comment by alzaia** [comment]
@mathieuboudreau for your comment above, you are right, this is an error as the integrity_test was coded before the suffix change and was not updated afterwards. 

So, we should remove the default argument IMO, and it would be more clean to put the suffix change within axon_segmentation() as this is the most low-level function that can be used to do the segmentation. I can do it (or maybe you planned to do it?).

**Comment by mathieuboudreau** [comment]
> I can do it (or maybe you planned to do it?).

@alzaia doesn't matter to me – it should be a quick fix. I can take a crack at it if you're busy.

**Comment by alzaia** [comment]
@mathieuboudreau Ok I will do it!
